version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get github.com/aedipamoss/stationery
      - run: stationery
      - store_artifacts:
          path: out
          destination: site
      - run: ./.circleci/deploy-ghpages.sh
